### ISSUE TITLE
/tool_deps/_conda/bin/bdss: not found

### ISSUE THREAD

**Issue by MingChen0919** [bcuser30/ML_GalaxyQueue#2]
###System information
Please enter the following information (if able). 

**Galaxy Instance**: test 

### Issue description 

Running the **aurora_bdss** tool gives this error: `/tool_deps/_conda/bin/bdss: not found`

To reproduce the error, enter input value as below and click **Execute**:
<img width="705" alt="screen shot 2018-05-29 at 10 14 34 am" src="https://user-images.githubusercontent.com/1262709/40664521-1ea6b9f6-6329-11e8-9373-65a530e90c3c.png">

On the galaxy history window, you will see this:

<img width="438" alt="screen shot 2018-05-29 at 10 16 40 am" src="https://user-images.githubusercontent.com/1262709/40664667-72255a1a-6329-11e8-8a60-33098cb1040e.png">

**Comment by heh30** [comment]
I updated rmarkdown_report.RMD; lines 83 and 105 so the bdss executable location was correct.  I first tried without using the full path, but that didn't work.  There is a new error when I run the tool.

[36m2018-05-29 12:28:12,493 INFO - Requesting transfers for ftp://ftp.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR039/SRR039885/SRR039885.sra[0m
[33m2018-05-29 12:28:13,242 WARNING - Request for transfers failed[0m
[36m2018-05-29 12:28:13,251 INFO - 1 transfer(s) for ftp://ftp.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR039/SRR039885/SRR039885.sra[0m
[36m2018-05-29 12:28:13,251 INFO - ------------------[0m
[36m2018-05-29 12:28:13,252 INFO - Transfer(ftp://ftp.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR039/SRR039885/SRR039885.sra, curl, {})[0m
[36m2018-05-29 12:28:13,252 INFO - Transferring ftp://ftp.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR039/SRR039885/SRR039885.sra with curl[0m
[36m2018-05-29 12:28:20,115 INFO - Success. Transferred 103771478 bytes in 6 seconds[0m
[36m2018-05-29 12:28:20,116 INFO - Verifying transfer from ftp://ftp.ncbi.nlm.nih.gov/sra/sra-instant/reads/ByRun/sra/SRR/SRR039/SRR039885/SRR039885.sra[0m
[33m2018-05-29 12:28:21,531 WARNING - Unable to verify with MD5 Checksum[0m
[36m2018-05-29 12:28:21,543 INFO - Transfer successful[0m
sh: 1: fastq-dump: not found

**Comment by MingChen0919** [comment]
i think i know how to fix the fastq-dump issue. What's the correct path to bdss? i need to update that in my tool repository first.

**Comment by heh30** [comment]
/main/sites/galaxy/test-galaxy/tools/_conda/bin/bdss

I don’t like that it’s the full path though…

For production it will be /main/sites/galaxy/galaxy/tools/_conda/bin/bdss

It would be ideal if tools/_conda/bin/bdss could be specified, but I'd tried that and it also failed.  It seems like we may be missing some sort of environment variable or something

**Comment by MingChen0919** [comment]
Thanks. the bdss tool was a manually installed tool. so far it can't be installed automatically during installing the galaxy tool. For this specific tool, we have to provide the full path.

**Comment by heh30** [comment]
were you able to fix the fastq-dump issue?

**Comment by MingChen0919** [comment]
yes, this issue can be closed.
