### ISSUE TITLE
/local/sites/galaxy/tools/_conda/envs/mulled-v1-6169a66b5083411fdb10c87f4d7f1: bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by MingChen0919** [bcuser30/ML_GalaxyQueue#5]
###System information
Please enter the following information (if able). 

**Galaxy Instance: test**

### Issue description 
Run the **bowtie2** and **hisat2** mapping tools generate the following error:

```
Fatal error: Exit code 126 ()
/main/sites/galaxy/test-galaxy/htdocs/database/jobs_directory/003/3731/tool_script.sh: /main/sites/galaxy/test-galaxy/tools/_conda/envs/mulled-v1-6169a66b5083411fdb10c87f4d7f16afa632dffd8fc63e9b16859d45e6ed2ad9/bin/bowtie2-build: /local/sites/galaxy/tools/_conda/envs/mulled-v1-6169a66b5083411fdb10c87f4d7f1: bad interpreter: No such file or directory
```

To reproduce the error, please run the bowtie2 tool as below:

<img width="1237" alt="screen shot 2018-05-30 at 3 08 09 pm" src="https://user-images.githubusercontent.com/1262709/40742176-a1a40eb0-641b-11e8-9e00-3f45b2ab5e9b.png">

**Comment by MingChen0919** [comment]
this might be caused by the length limitation for shebang in the tool script. See this: https://biostar.usegalaxy.org/p/27086/.  The path in the error message is only part of actual path in the tool script.
path in the error message: `/local/sites/galaxy/tools/_conda/envs/mulled-v1-6169a66b5083411fdb10c87f4d7f1`
actual path in the tool script file: `/local/sites/galaxy/tools/_conda/envs/mulled-v1-6169a66b5083411fdb10c87f4d7f16afa632dffd8fc63e9b16859d45e6ed2ad9/bin/python`

**Comment by heh30** [comment]
Yes, length limitation with conda is part of the problem.  /local/sites being in the path is also an issue.  I've resolved the /local/sites piece, but need to resolve the length issue

**Comment by heh30** [comment]
I've manually updated conda, as recommended

galaxy@galaxy:~$ /main/sites/galaxy/test-galaxy/tools/_conda/bin/conda info

     active environment : None
       user config file : /u/galaxy/.condarc
 populated config files : 
          conda version : 4.5.4
    conda-build version : 3.0.10
         python version : 3.5.2.final.0
       base environment : /main/sites/galaxy/galaxy/tools/_conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /main/sites/galaxy/galaxy/tools/_conda/pkgs
                          /u/galaxy/.conda/pkgs
       envs directories : /main/sites/galaxy/galaxy/tools/_conda/envs
                          /u/galaxy/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.4 requests/2.8.1 CPython/3.5.2 Linux/4.8.0-040800-generic ubuntu/16.04 glibc/2.23
                UID:GID : 1021:802
             netrc file : None
           offline mode : False

I did encounter an error, but I also may not have been using proper input files.  Please try again and let me know how it goes.

**Comment by heh30** [comment]
ugh, update of conda seems to have broken usage of the cluster.

**Comment by MingChen0919** [comment]
ok, i'll try when the galaxy server is up.

**Comment by heh30** [comment]
I'm in the process of rolling back the conda update to see if I can track down why it's causing problems.  Ability to use the cluster is pretty important.

**Comment by MingChen0919** [comment]
fixed by removing tool dependencies and re-installing the tools.

**Comment by heh30** [comment]
Also needed for this fix was to have the shared/mounted directory structure be much shorter.  Test is mounted at /galaxy/test on all the cluster nodes and a mount -o bind was performed on the galaxy server.  

/main/sites/galaxy/test-galaxy was the old shared path, the new shared path is /galaxy/test.
