### ISSUE TITLE
Proxy Error when install aurora_htseq from galaxy test tool shed

### ISSUE THREAD

**Issue by MingChen0919** [bcuser30/ML_GalaxyQueue#7]
###System information
Please enter the following information (if able). 

**Galaxy Instance: test**

### Issue description 
When installing the **aurora_htseq** tool from the Galaxy Test Tool Shed, I got this error:

<img width="1249" alt="screen shot 2018-05-31 at 3 45 16 pm" src="https://user-images.githubusercontent.com/1262709/40804562-b0bcf88e-64e9-11e8-89b5-724e9e97b980.png">

To reproduce this error, go to **Admin->install new tools->Galaxy Test Tool Shed**, search for **aurora_htseq** tool and install the tool.

**Comment by MingChen0919** [comment]
after removing all tool dependencies for aurora_htseq and uninstall all different versions, i was able to re-install the tool successfully.

**Comment by heh30** [comment]
Can this be closed, Ming?

**Comment by MingChen0919** [comment]
yes
